# Generated by Django 2.2.4 on 2019-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
